Remove reference to unused config value
tidalmigrations/machine_stats pull request #108
Opened 2021-11-12 20:54 UTC by justinbarclay

Update documentation and example to reflect actual usage

2021-11-15 19:07 UTC, przmv commented on unix/README.md
> +machine-stats --process-stats true
I added some debug output and it looks like `process_stats` is always true with:
- `--process-stats true`
- `--process-stats=true`
- `--process-stats false`
- `--process-stats=false`
- no `--process-stats` flag at all

Please check the [`argparse` documentation](https://docs.python.org/3/library/argparse.html) and search for `store_true` or `store_false`.

2021-11-15 19:08 UTC, przmv requested changes
Documentation is good, but the actual behavior is buggy.

2021-11-15 19:20 UTC, przmv commented
Not related to this particular PR, but while running `machine-stats` with process stats enabled I got the error: `ERROR! petr@34.133.209.146: 'vmsize'`. Looking into the code, I discovered that there's no check for `vmsize` property to exist in the `status` dictionary.

2021-11-16 20:52 UTC, justinbarclay commented
How do you actually run machine stats as you're developing it, in python? I am stuck. I used to just run __init__ but that no longer works. You give instructions on how to install dependencies locally but not how to run the app as your develping it.

2021-11-16 20:58 UTC, justinbarclay commented
For reference I am trying: 
```
✦ ❯ python3 src/machine_stats/__init__.py --process-stats True --cpu-utilization-timeout 0
Traceback (most recent call last):
  File "/home/justin/dev/tidal/machine_stats/unix/src/machine_stats/__init__.py", line 19, in <module>
    os.environ[k] = v
  File "/usr/lib/python3.9/os.py", line 684, in __setitem__
    value = self.encodevalue(value)
  File "/usr/lib/python3.9/os.py", line 756, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not bool
```

2021-11-16 21:15 UTC, przmv commented
> For reference I am trying:
> 
> ```
> ✦ ❯ python3 src/machine_stats/__init__.py --process-stats True --cpu-utilization-timeout 0
> Traceback (most recent call last):
>   File "/home/justin/dev/tidal/machine_stats/unix/src/machine_stats/__init__.py", line 19, in <module>
>     os.environ[k] = v
>   File "/usr/lib/python3.9/os.py", line 684, in __setitem__
>     value = self.encodevalue(value)
>   File "/usr/lib/python3.9/os.py", line 756, in encode
>     raise TypeError("str expected, not %s" % type(value).__name__)
> TypeError: str expected, not bool
> ```

This was fixed in https://github.com/tidalmigrations/machine_stats/commit/44dd3b9ea018d34eeac84eb3018a7ca451cee736

2021-11-16 21:20 UTC, przmv commented
> How do you actually run machine stats as you're developing it, in python? I am stuck. I used to just run **init** but that no longer works. You give instructions on how to install dependencies locally but not how to run the app as your develping it.

1—3 are prerequisites, 4—5 are for actual development and running the dev version

1. Install `pipenv`
2. `cd unix`
3. `pipenv install && pipenv install --dev`
4. `vi src/machine_stats/__init__.py`
5. `pipenv run machine_stats --help`

2021-11-16 21:23 UTC, jmariomejiap commented
> How do you actually run machine stats as you're developing it, in python? I am stuck. I used to just run **init** but that no longer works. You give instructions on how to install dependencies locally but not how to run the app as your develping it.

We should adjust the instructions to include how to run it locally. Can you please @przmv update documentation?

2021-11-16 21:27 UTC, justinbarclay commented
Awesome, I am able to run the init file directly now 😄

2021-11-16 21:31 UTC, przmv commented
> > How do you actually run machine stats as you're developing it, in python? I am stuck. I used to just run **init** but that no longer works. You give instructions on how to install dependencies locally but not how to run the app as your develping it.
> 
> We should adjust the instructions to include how to run it locally. Can you please @przmv update documentation?

Submitted a new PR https://github.com/tidalmigrations/machine_stats/pull/110

2021-11-16 22:06 UTC, justinbarclay commented
> Not related to this particular PR, but while running `machine-stats` with process stats enabled I got the error: `ERROR! petr@34.133.209.146: 'vmsize'`. Looking into the code, I discovered that there's no check for `vmsize` property to exist in the `status` dictionary.

Thats weird, I found nothing to indicate that the vmsize property might not exist in the status file. The closest to a reference that I could find is [here](https://www.kernel.org/doc/html/latest/filesystems/proc.html). @przmv I'll fix this in a subsequent MR, but do you know if it's safe to assume any of these fields would exist in the status file?

2021-11-17 16:33 UTC, justinbarclay commented
and here is a video demonstrating the changes to be... uh closer to ~our expectations~ working

https://user-images.githubusercontent.com/6868388/142241579-f3e2fe50-1987-48ca-a183-c1ec90eb7536.mp4

2021-11-18 20:03 UTC, przmv approved these changes
LGTM!

2021-11-18 21:33 UTC, merged