Update doc and fix py3 support
tidalmigrations/machine_stats pull request #9
Opened 2020-08-26 23:32 UTC by fortran01

2020-08-27 12:20 UTC, pshevtsov requested changes

2020-08-27 12:20 UTC, pshevtsov commented on README.md
> +### Known issues
What is the issue? Why may it happen?

2020-08-27 12:20 UTC, pshevtsov commented on unix/runner
> +        # host = result._host
No need to comment old code, we can retrieve it from git history if needed.

2020-08-27 12:20 UTC, pshevtsov commented on unix/runner
> +            # 'storage_allocated_gb': storage_allocated_gb(facts),
Why not gathering storage use info?

2020-08-27 19:11 UTC, fortran01 commented
Clarification: I was just able to confirm it works with RHEL7, py2.7 and the same Ansible version baked into requirements.txt :thumbsup_all:

I will confirm py3 with venv later.

2020-08-27 19:16 UTC, fortran01 commented on README.md
> +### Known versions to work
@pshevtsov WDYT?

2020-08-31 14:34 UTC, dcolebatch commented
Are we going to abandon this PR now @fortran01 ?

2020-08-31 14:37 UTC, fortran01 commented
> Are we going to abandon this PR now @fortran01 ?

I am going to re-test `py3` on RHEL7 and sync this with the latest changes in `master`.

2021-03-02 15:29 UTC, prees1 commented
Closing this PR @fortran01. @pshevtsov has recently made some merges that cover the goal here. Here are @pshevtsov recent related PRs that are merged, https://github.com/tidalmigrations/machine_stats/pull/20, https://github.com/tidalmigrations/machine_stats/pull/19, https://github.com/tidalmigrations/machine_stats/pull/17

If anything on this is PR here is still needed feel free to reopen or let me know.

2021-03-02 15:29 UTC, closed without merging